context:
  version: "0.21.9"

package:
  name: xplr
  version: ${{ version }}

source:
  url: https://github.com/sayanarijit/xplr/archive/v${{ version }}.tar.gz
  sha256: 345400c2fb7046963b2e0fcca8802b6e523e0fb742d0d893cb7fd42f10072a55

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make

tests:
  - script:
      - xplr --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Hackable, minimal, fast TUI file explorer
  homepage: https://github.com/sayanarijit/xplr
  repository: https://github.com/sayanarijit/xplr

extra:
  recipe-maintainers:
    - danielnachun
