context:
  version: "1.0.0"

package:
  name: xplr
  version: ${{ version }}

source:
  url: https://github.com/sayanarijit/xplr/archive/v${{ version }}.tar.gz
  sha256: 72e9b53552b4fce61805c32c739d8d7db4723f80b4586c9eb5e9921e1ae32ce0

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make

tests:
  - script:
      - xplr --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Hackable, minimal, fast TUI file explorer
  homepage: https://github.com/sayanarijit/xplr
  repository: https://github.com/sayanarijit/xplr

extra:
  recipe-maintainers:
    - danielnachun
